export const shortcuts = {
  createFolder: ["Alt", "N"],
  cut: ["Control", "X"],
  copy: ["Control", "C"],
  paste: ["Control", "V"],
  rename: ["F2"],
  delete: ["Delete"],
  open: ["Enter"],
  selectAll: ["Control", "A"],
  selectArrowUp: ["Shift", "ArrowUp"],
  selectArrowDown: ["Shift", "ArrowDown"],
  navigateUp: ["ArrowUp"],
  navigateDown: ["ArrowDown"],
  jumpToFirst: ["Home"],
  jumpToLast: ["End"],
  refresh: ["F5"],
  cancel: ["Escape"],
};
